#!/bin/bash

if [ "$1" = "init" ];then
   mkdir .ipfvcs
   mkdir .ipfvcs/objects
   mkdir .ipfvcs/objects/files
   mkdir .ipfvcs/objects/files/lfs
#   echo "Shouldn't make these dirs in case .ipfvcs already exist"
   echo "Initialized empty IPFVCS repository in $(pwd)/.ipfvcs/"
fi

if [ "$1" = "hash-object" ];then
if [ "$2" != "--stdin" ];then
   var="$(ipfs add -q --only-hash $2)"
   echo "$var"
   var=${var:2}
#thanks for https://stackoverflow.com/a/11470727/5623661
if [ "$3" = "-w" ];then
   firstwochars=$(echo "${var}" | head -c2)
   mkdir ".ipfvcs/objects/files/$firstwochars"
#   echo "Shouldn't make this dir in case it already exist"
#thanks for https://stackoverflow.com/a/1405641/5623661
   firstwocharslast=${var:2}
   cat "$2" > ".ipfvcs/objects/files/$firstwochars/$firstwocharslast"
#   echo "Shouldn't make this file in case it already exist"
fi
fi
fi
